### PR TITLE
🛠 Add Github Action

### PR DESCRIPTION
**Pull request by mambax**
Downloads executable and links it to the runners' path
Also clarifies some documentation

Notes:
- It might be a good idea to tarball the executable (then the setup script must be changed of course)
- Somehow, the HCL `--config` does not make sense yet. To whom do I pass that argument

### CODE REVIEW

**Comment by mambax** [comment]
@dee-kryvenko Please review.

**Comment by mambax** [comment]
A team member of mine has found that it does not yet work as expected, will update it.

**Comment by mambax** [comment]
It was an internal problem for us when setting up the runners, please review or merge 🍻

**Comment by mambax** [comment]
@dee-kryvenko any feedback here? I kind of need that action, otherwise I will merge to our internal GHSE for now 😞.

**Review by dee-kryvenko — APPROVED** [review]

**Comment by dee-kryvenko** [comment]
Thanks @mambax for the contribution!

**Pull request merged**
